
trigger:
- develop

variables:
  dockerRegistryServiceConnection: '4c5cfaad-792b-4ae6-a84d-fc9af9f5245e'
  imageRepository: 'minhasreceitasapp'
  containerRegistry: 'apiminhasreceitas.azurecr.io'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: Build and push an image to container registry
  inputs:
    command: buildAndPush
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    containerRegistry: $(dockerRegistryServiceConnection)
    tags: |
      latest
      $(tag)

   
    
