trigger:
- develop

variables:
  imageRepository: 'minhasreceitasapp'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: DownloadSecureFile@1
  displayName: Download appsettings.json
  name: appsettings
  inputs:
    secureFile: 'appsettings.Production.json'

- script: |
    cp $(appsettings.secureFilePath) src/Backend/MinhasReceitasApp.API
  displayName: Copia arquivo de configuração seguro

- task: Docker@2
  displayName: Build e push da imagem Docker
  inputs:
    command: buildAndPush
    repository: $(imageRepository)
    dockerfile: $(dockerfilePath)
    containerRegistry: $(DOCKER_REGISTRY_SERVICE_CONNECTION) 
    tags: |
      latest
      $(tag)
