
trigger:
- master

variables:
  dockerRegistryServiceConnection: 'dd63e0f4-97c1-4ff7-b2b8-cc290fc21b74'
  imageRepository: 'apiminhasreceitas'
  containerRegistry: 'apiminhasreceitas.azurecr.io'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'

pool:
      vmImage: 'ubuntu-latest'

steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          latest
          $(tag)
    
   
